<?php

namespace Forum\Bundle\ForumBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ForumPost extends EntityRepository
{
}
