parameters:
    regions: AppBundle\Entity\Region
    city:     AppBundle\Entity\City
    organize: AppBundle\Entity\Organize
    news: AppBundle\Entity\News
    partner: AppBundle\Entity\Partner
#    photo: AppBundle\Entity\Photo

services:

######################################################## Fixtures ######################################################

    AppBundle\DataFixtures\ORM\RegionFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\CityFixtures:
        tags: [doctrine.fixture.orm]

    AppBundle\DataFixtures\ORM\UserFixtures:
        tags: [doctrine.fixture.orm]

######################################################## Handlers ######################################################

    region.handler:
        class: AppBundle\Handler\RegionHandler
        arguments: ['@service_container', '%regions%']

    city.handler:
        class: AppBundle\Handler\CityHandler
        arguments: ['@service_container', '%city%']

    organize.handler:
        class: AppBundle\Handler\OrganizeHandler
        arguments: ['@service_container', '%organize%']

    news.handler:
        class: AppBundle\Handler\NewsHandler
        arguments: ['@service_container', '%news%']

    partner.handler:
       class: AppBundle\Handler\PartnerHandler
       arguments: ['@service_container', '%partner%']

######################################################## Admin panel ###################################################

    admin.region:
        class: AppBundle\Admin\RegionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-globe"></i>', group: "Местоположения", label: "Регионы" }
        arguments:
            - ~
            - %regions%
            - 'SonataAdminBundle:CRUD'

    admin.city:
        class: AppBundle\Admin\CityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-globe"></i>', group: "Местоположения", label: "Города" }
        arguments:
            - ~
            - '%city%'
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AppBundle]]

    admin.organize:
        class: AppBundle\Admin\OrganizeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-globe"></i>', group: "Местоположения", label: "Организации" }
        arguments:
            - ~
            - '%organize%'
            - 'SonataAdminBundle:CRUD'
            - '@service_container'

    admin.partner:
        class: AppBundle\Admin\PartnerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-diamond "></i>', group: "Партнеры", label: "Партнеры" }
        arguments:
            - ~
            - '%partner%'
            - 'SonataAdminBundle:CRUD'

    admin.news:
        class: AppBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-newspaper-o"></i>', group: "Новости", label: "Новости" }
        arguments:
            - ~
            - '%news%'
            - 'SonataAdminBundle:CRUD'