# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    java: /usr/bin/java
    filters:
        less:
            node: /usr/bin/node
            node_paths: ['/usr/lib/node_modules','/usr/local/lib/node_modules']
            apply_to: "\.less$"
        cssrewrite: ~
        uglifyjs2:
            bin: %kernel.root_dir%/Resources/node_modules/.bin/uglifyjs
            apply_to: "\.js$"
        uglifycss:
            bin: %kernel.root_dir%/Resources/node_modules/.bin/uglifycss

