############################################### Sonata Bundless ########################################################

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu:    true # used to display the menu in profile pages
        sonata.user.block.account: true # used to display menu option (login option)
        sonata.block.service.text: true # used to if you plan to use Sonata user routes
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    class:
        user: Application\Sonata\UserBundle\Entity\User
        group: Application\Sonata\UserBundle\Entity\Group