parameters:
    forum: Forum\Bundle\ForumBundle\Entity\Forum
    forum_post: Forum\Bundle\ForumBundle\Entity\ForumPost
    voting: Forum\Bundle\ForumBundle\Entity\Voting
    voting_params: Forum\Bundle\ForumBundle\Entity\VotingParams
    mail: AppBundle\Entity\Mail


services:
######################################################## Handlers ######################################################
    forum.handler:
         class: Forum\Bundle\ForumBundle\Handler\ForumHandler
         arguments: ['@service_container', '%forum%']

    forum_post.handler:
         class: Forum\Bundle\ForumBundle\Handler\ForumPostHandler
         arguments: ['@service_container', '%forum_post%']

    voting.handler:
         class: Forum\Bundle\ForumBundle\Handler\VotingHandler
         arguments: ['@service_container', '%voting%']

    voting_params.handler:
         class: Forum\Bundle\ForumBundle\Handler\VotingParamsHandler
         arguments: ['@service_container', '%voting_params%']

    mail.handler:
        class: AppBundle\Handler\MailHandler
        arguments: ['@service_container', '%mail%']

######################################################## Admin panel ###################################################

    admin.forum:
        class: Forum\Bundle\ForumBundle\Admin\ForumAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-list-ul"></i>', group: "Форум", label: "Форумы" }
        arguments:
            - ~
            - '%forum%'
            - 'SonataAdminBundle:CRUD'
            - '@service_container'

    admin.forum.post:
        class: Forum\Bundle\ForumBundle\Admin\ForumPostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-list-ul"></i>', group: "Форум", label: "Посты", show_in_dashboard: false }
        arguments:
            - ~
            - '%forum_post%'
            - 'SonataAdminBundle:CRUD'
            - '@service_container'

    admin.voting:
        class: Forum\Bundle\ForumBundle\Admin\VotingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-list-ul"></i>', group: "Форум", label: "Голосование" } #, show_in_dashboard: false }
        arguments:
            - ~
            - '%voting%'
            - 'SonataAdminBundle:CRUD'

    admin.voting_params:
        class: Forum\Bundle\ForumBundle\Admin\VotingParamsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-list-ul"></i>', group: "Форум", label: "Параметры голосования" } #, show_in_dashboard: false }
        arguments:
            - ~
            - '%voting_params%'
            - 'SonataAdminBundle:CRUD'