<?php

/**
 * @author:     aat <aat@norse.digital>
 *
 * @copyright   Copyright (C) 2015 NXC AS.
 * @date: 09 07 2015
 */
namespace App\CoreBundle\Repository;

use App\CoreBundle\Entity\Menu;
use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    /**
     * Get Menu list without product.
     *
     * @return array
     */
    public function getMenuList()
    {
        $menuList = $this->createQueryBuilder('m')
            ->select('m.id', 'm.name', 'm.slug', 'm.status', 'm.priority')
            ->addOrderBy('m.priority')
            ->getQuery()
            ->getResult();

        return $menuList;
    }

    /**
     * Get Menu item without product.
     *
     * @param int $id
     *
     * @return Menu
     */
    public function getMenu($id)
    {
        $menu = $this->createQueryBuilder('m')
            ->select('m.id', 'm.name', 'm.slug', 'm.status', 'm.priority')
            ->where('m.id = :menu_id')
            ->setParameter('menu_id', $id)
            ->getQuery()
            ->getResult();

        return $menu;
    }
}
