<?php

/**
 * @author:     aat <aat@norse.digital>
 *
 * @copyright   Copyright (C) 2015 NXC AS.
 * @date: 16 09 2015
 */
namespace App\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuProductsRepository extends EntityRepository
{
    /**
     * Get max priority value
     * @param $menu
     * @return int
     */
    public function getMaxPriority($menu)
    {
        $maxPriority = $this->createQueryBuilder('mp')
            ->select('MAX(mp.priority)')
            ->where('mp.menu = :menu')
            ->setParameter('menu', $menu)
            ->getQuery()
            ->getResult();

        return $maxPriority[0][1];
    }
}
