<?php

namespace App\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SeoRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    /**
     * @param $query
     * @return array
     */
    public function getOrderPhoneNameByQuery($query)
    {
        $orderList = $this->createQueryBuilder('o')
            ->select('o.phone, c.firstName, c.lastName')
            ->leftJoin('AppCoreBundle:Customer', 'c', 'WITH', 'o.phone = c.phone')
            ->where('o.phone LIKE :query')
            ->orWhere('c.firstName LIKE :query')
            ->orWhere('c.lastName LIKE :query')
            ->setParameter('query', '%' .$query. '%')
            ->getQuery()
            ->getResult();

        return $orderList;
    }
}
