<?php

namespace App\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductVariantRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProductVariantRepository extends EntityRepository
{
}
