<?php

namespace App\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * RestaurantOpeningHourRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RestaurantOpeningHourRepository extends EntityRepository
{
    /**
     * @param $restaurantId
     * @param bool|false $date
     * @return bool|mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getDeviantOpeningHours($restaurantId, $date = false)
    {
        if ($date === false) {
            $date = date('Y-m-d');
        }

        $query = $this
            ->createQueryBuilder('roh')
            ->where('roh.restaurant_id = :restaurant AND roh.date = :date')
            ->setParameter('restaurant', $restaurantId)
            ->setParameter('date', $date)
            ->getQuery();

        try {
            $openingHours = $query->getSingleResult();
        } catch (NoResultException $e) {
            $openingHours = false;
        }

        return $openingHours;
    }
}
