<?php

namespace App\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RestaurantRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends EntityRepository
{
    /**
     * @param array $defaultVal
     * @return mixed
     *
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function setDefaultTimes(array $defaultVal = [])
    {
        return $this
            ->createQueryBuilder('r')
            ->update('AppCoreBundle:Restaurant', 'r')
            ->set('r.timeTakeaway', '?20')
            ->set('r.timeDelivery', '?60')
            ->set('r.warrantyVoided', '?0')
            ->setParameter('20', $defaultVal['takeaway'])
            ->setParameter('60', $defaultVal['delivery'])
            ->setParameter('0', $defaultVal['warranty_voided'])
            ->getQuery()->execute();
    }
}
