web_rules:
    path:     /rules
    defaults: { _controller: WebBundle:Default:index }

web_contacts:
    path:     /contacts
    defaults: { _controller: WebBundle:Default:contacts }

web_about_us:
    path:     /about_us
    defaults: { _controller: WebBundle:Default:about }

web_blog:
    path:     /blog
    defaults: { _controller: WebBundle:Blog:index }

web_city:
    path:     /city/{url}
    defaults: { _controller: WebBundle:Default:city }


web_news:
    path:     /news/
    defaults: { _controller: WebBundle:Default:news }
    requirements:
        id: \d+

web_region:
    path:     /region/{url}
    defaults: { _controller: WebBundle:Default:region }