<?php

namespace CoreBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * VotingParamsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class VotingParamsRepository extends EntityRepository
{
}
